-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 14:33:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema prodavnica_patika
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prodavnica_patika
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prodavnica_patika` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `prodavnica_patika` ;

-- -----------------------------------------------------
-- Table `prodavnica_patika`.`patike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodavnica_patika`.`patike` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` TEXT NOT NULL,
  `brend` TEXT NOT NULL,
  `namena` TEXT NOT NULL,
  `cena` FLOAT NOT NULL,
  `slika` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table `prodavnica_patika`.`korisnici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodavnica_patika`.`korisnici` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `korisnicko_ime` TEXT NOT NULL,
  `lozinka` TEXT NOT NULL,
  `ime` TEXT NOT NULL,
  `prezime` TEXT NOT NULL,
  `adresa` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `telefon` TEXT NOT NULL,
  `admin` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


INSERT INTO korisnici VALUES(0,"test","test","admin","","","","",1);

-- -----------------------------------------------------
-- Table `prodavnica_patika`.`kupovine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodavnica_patika`.`kupovine` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `datum` DATETIME NOT NULL,
  `korisnik_id` INT(11) NOT NULL,
  `patika_id` INT(11) NOT NULL,
  `patika_cena` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `korisnik_id` (`korisnik_id` ASC) VISIBLE,
  INDEX `patika_id` (`patika_id` ASC) VISIBLE,
  CONSTRAINT `patika_id`
    FOREIGN KEY (`patika_id`)
    REFERENCES `prodavnica_patika`.`patike` (`id`),
  CONSTRAINT `korisnik_id`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `prodavnica_patika`.`korisnici` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
